### PR TITLE
cnx-contrib: add leftwm

### PR DESCRIPTION
**Pull request by Sh4d1**
Also bump the rust version and edition and fix rustdoc for features only
modules.

Fixes https://github.com/mjkillough/cnx/issues/60

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

**Review by psibi — CHANGES_REQUESTED** [review]
Thank you! this looks good.

You may need to likely change the github workflows file for the proper rust version: https://github.com/mjkillough/cnx/blob/master/.github/workflows/ci.yml#L19

Also, can you update the README with the description of this widget  and also the built in section (https://docs.rs/cnx/latest/cnx/#built-in-widgets) ?

**Comment by Sh4d1** [comment]
Yes, should be good, added a `cargo clippy --fix` as well

**Review by psibi — APPROVED** [review]
LGTM. Can you update the changelog too ?

**Comment by psibi** [comment]
Thank you!

**Pull request merged**
